version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=app-local-lexicon.app
      - DB_URL=mongodb://mongodb/lexiconjs
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest

  load-balancer:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure